services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"  # Admin API
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./conf:/etc/caddy
      - ./caddy-data:/data
      - ./caddy_config:/config
      - ./test-static:/srv/test-static:ro  # Mount test files as read-only